// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chvgtldjpkpuuousfshe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNodmd0bGRqcGtwdXVvdXNmc2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTMwNjQsImV4cCI6MjA2NTQ4OTA2NH0.VI-i_cIHG3-cZ0wXlgqnrzr3rNqJyDuiUXr9UNzM1e8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);